### ISSUE TITLE
webob 1.5 is broken 

### ISSUE THREAD

**Issue by ei-grad** [klen/muffin#15]
https://github.com/Pylons/webob/issues/121

```
> py.test -sx --tb=native
...
========================================== FAILURES ===========================================
______________________________________ test_handler_func ______________________________________
Traceback (most recent call last):
  File "/home/ei-grad/.virtualenvs/edapi-muffin/lib/python3.5/site-packages/webob/response.py", line 266, in _status__set
    status_code = int(value.split()[0])
ValueError: invalid literal for int() with base 10: 'HTTP/1.0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ei-grad/repos/muffin/tests/test_handlers.py", line 12, in test_handler_func
    response = client.get('/test')
  File "/home/ei-grad/.virtualenvs/edapi-muffin/lib/python3.5/site-packages/webtest/app.py", line 322, in get
    expect_errors=expect_errors)
  File "/home/ei-grad/.virtualenvs/edapi-muffin/lib/python3.5/site-packages/webtest/app.py", line 605, in do_request
    res = req.get_response(app, catch_exc_info=True)
  File "/home/ei-grad/.virtualenvs/edapi-muffin/lib/python3.5/site-packages/webob/request.py", line 1313, in send
    application, catch_exc_info=True)
  File "/home/ei-grad/.virtualenvs/edapi-muffin/lib/python3.5/site-packages/webob/request.py", line 1281, in call_application
    app_iter = application(self.environ, start_response)
  File "/home/ei-grad/.virtualenvs/edapi-muffin/lib/python3.5/site-packages/webtest/lint.py", line 198, in lint_app
    iterator = application(environ, start_response_wrapper)
  File "/home/ei-grad/repos/muffin/muffin/pytest.py", line 95, in handle
    res = webob.Response.from_file(handler.transport)
  File "/home/ei-grad/.virtualenvs/edapi-muffin/lib/python3.5/site-packages/webob/response.py", line 194, in from_file
    app_iter=(),
  File "/home/ei-grad/.virtualenvs/edapi-muffin/lib/python3.5/site-packages/webob/response.py", line 107, in __init__
    self.status = status
  File "/home/ei-grad/.virtualenvs/edapi-muffin/lib/python3.5/site-packages/webob/response.py", line 268, in _status__set
    raise ValueError('Invalid status code, integer required.')
ValueError: Invalid status code, integer required.
!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: stopping after 1 failures !!!!!!!!!!!!!!!!!!!!!!!!!!!!
================================== 1 failed in 0.11 seconds ==================================```

**Comment by ei-grad** [comment]
```pip install 'webob<1.5'``` solves the problem

**Comment by klen** [comment]
Thank you for the feedback!

**Comment by bertjwregeer** [comment]
Using a version older than WebOb 1.5.0 shouldn't make a difference, that bug report you linked to is much older than WebOb 1.5.0: What would be more interesting is to find out why using an older WebOb does work correctly...

**Comment by bertjwregeer** [comment]
I can't reproduce the above error...

Even with WebOb 1.5.0 on Python 3.5. Am

    (muffin) Sterling:muffin xistence$ py.test -sx --tb=native
    ============================================================================================== test session starts ==============================================================================================
    platform darwin -- Python 3.5.0, pytest-2.8.2, py-1.4.30, pluggy-0.3.1
    rootdir: /Users/xistence/Projects/muffin, inifile: setup.cfg
    plugins: muffin-0.2.1, pythonpath-0.7
    collected 23 items 

    tests/test_handlers.py [2015-10-13 11:00:29 -0600] [18786] [ERROR] Plugin is invalid: invalid.plugin
    [2015-10-13 11:00:29 -0600] [18786] [ERROR] No module named 'invalid'
    Traceback (most recent call last):
      File "/Users/xistence/Projects/muffin/muffin/app.py", line 94, in __init__
        self.install(plugin)
      File "/Users/xistence/Projects/muffin/muffin/app.py", line 134, in install
        module = import_module(module)
      File "/Users/xistence/.pyenv/versions/3.5.0/lib/python3.5/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 986, in _gcd_import
      File "<frozen importlib._bootstrap>", line 969, in _find_and_load
      File "<frozen importlib._bootstrap>", line 944, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
      File "<frozen importlib._bootstrap>", line 986, in _gcd_import
      File "<frozen importlib._bootstrap>", line 969, in _find_and_load
      File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
    ImportError: No module named 'invalid'
    ...
    tests/test_muffin.py ...../Users/xistence/.ve/muffin/lib/python3.5/site-packages/webtest/lint.py:359: WSGIWarning: Unknown REQUEST_METHOD: 'PROPFIND'
      WSGIWarning)
    .......
    tests/test_plugins.py .
    tests/test_tests.py ...
    tests/test_utils.py ....

    =========================================================================================== 23 passed in 0.22 seconds ===========================================================================================
    (muffin) Sterling:muffin xistence$ pip freeze
    aioauth-client==0.6.1
    aiohttp==0.17.4
    Babel==2.1.1
    beautifulsoup4==4.4.1
    cached-property==1.2.0
    chardet==2.3.0
    fake-factory==0.5.2
    gunicorn==19.3.0
    Jinja2==2.7.3
    MarkupSafe==0.23
    mixer==5.2.2
    -e git+git@github.com:klen/muffin.git@ad507ed4fc60e745bac194f2c41ca99f8f5d6352#egg=muffin-develop
    muffin-admin==0.1.3
    muffin-babel==0.0.6
    muffin-jinja2==0.1.0
    muffin-oauth==0.2.5
    muffin-peewee==0.4.0
    muffin-session==0.0.8
    peewee==2.6.4
    py==1.4.30
    pytest==2.8.2
    pytest-pythonpath==0.7
    pytz==2015.6
    six==1.10.0
    speaklater==1.3
    ujson==1.33
    waitress==0.8.10
    WebOb==1.5.0
    WebTest==2.0.18
    wtf-peewee==0.2.3
    WTForms==2.0.2

If I could reproduce the above error then I could at least make sure that the fix I just introduced into WebOb fixes this issue as well...

**Comment by klen** [comment]
@bertjwregeer I've already fixed the error in last version. Before there was an error in Muffin pytest integration, which didn't raise for webob < 1.5. From webop 1.5 it (webob) starts to check status assignments and the error appears.

**Comment by bertjwregeer** [comment]
@klen Ah, okay. Yes, I added the extra check because WebOb should not allow invalid HTTP responses to be generated (specifically, a status line should contain an integer and a status text), and I'd rather warn a developer/user of the issue than silently allowing it to pass.

Perfect :-)

**Comment by klen** [comment]
@bertjwregeer Ok, but looks like webob v. 1.5.1will break the Muffin tests again, as the Muffin tries to play around wrong webob behaviour, which has been fixed https://github.com/Pylons/webob/commit/4b83fb25f0c7f373835a7d988d3bbfa61616fd0b.

**Comment by bertjwregeer** [comment]
That fix I just applied will accept a `Response.from_file` that contains an HTTP status header, not, i.e. that original error that was raised above would have been fixed by that patch.

So now in WebOb the following two are allowed in the status line:

    HTTP/1.0 200 OK

and

    200 OK

These two will now properly be parsed and both result in a Response that has a status of `200 OK`.

Running `py.test` in Muffin with `master` from WebOb continues to function and no test failures are noted:

    (muffin) Sterling:muffin xistence$ py.test -xs
    ============================================================================================== test session starts ==============================================================================================
    platform darwin -- Python 3.5.0, pytest-2.8.2, py-1.4.30, pluggy-0.3.1
    rootdir: /Users/xistence/Projects/muffin, inifile: setup.cfg
    plugins: muffin-0.2.1, pythonpath-0.7
    collected 23 items 
    
    tests/test_handlers.py [2015-10-14 10:03:18 -0600] [22616] [ERROR] Plugin is invalid: invalid.plugin
    [2015-10-14 10:03:18 -0600] [22616] [ERROR] No module named 'invalid'
    Traceback (most recent call last):
      File "/Users/xistence/Projects/muffin/muffin/app.py", line 94, in __init__
        self.install(plugin)
      File "/Users/xistence/Projects/muffin/muffin/app.py", line 134, in install
        module = import_module(module)
      File "/Users/xistence/.pyenv/versions/3.5.0/lib/python3.5/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 986, in _gcd_import
      File "<frozen importlib._bootstrap>", line 969, in _find_and_load
      File "<frozen importlib._bootstrap>", line 944, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
      File "<frozen importlib._bootstrap>", line 986, in _gcd_import
      File "<frozen importlib._bootstrap>", line 969, in _find_and_load
      File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
    ImportError: No module named 'invalid'
    ...
    tests/test_muffin.py ...../Users/xistence/.ve/muffin/lib/python3.5/site-packages/webtest/lint.py:359: WSGIWarning: Unknown REQUEST_METHOD: 'PROPFIND'
      WSGIWarning)
    .......
    tests/test_plugins.py .
    tests/test_tests.py ...
    tests/test_utils.py ....
    
    =========================================================================================== 23 passed in 0.23 seconds ===========================================================================================
    (muffin) Sterling:muffin xistence$ pip freeze | grep WebOb
    WebOb==1.6.0a0

**Comment by klen** [comment]
@bertjwregeer Wow, ok. Thank you!
