### ISSUE TITLE
NameError when providing unavailable config module

### ISSUE THREAD

**Issue by MarSoft** [klen/muffin#38]
Tested on Python `3.5.1`
When I specify not-existing module name as --config option or in CONFIG kw, I get the following output when starting app:
```
[2016-03-16 05:53:03 +0300] [9406] [INFO] Starting gunicorn 19.4.5
[2016-03-16 05:53:03 +0300] [9406] [INFO] Listening at: http://0.0.0.0:5002 (9406)
[2016-03-16 05:53:03 +0300] [9406] [INFO] Using worker: muffin.worker.GunicornWorker
[2016-03-16 05:53:03 +0300] [9449] [INFO] Booting worker with pid: 9449
ERROR:asyncio:Error in start callback
application: <Application: test>
Traceback (most recent call last):
  File "/tmp/muffin/muffin/app.py", line 188, in start
    res = cb(self, *args, **kwargs)
  File "/tmp/muffin/muffin/app.py", line 131, in <lambda>
    lambda app: app.logger.error("Error importing %s: %s", module, exc))
NameError: free variable 'exc' referenced before assignment in enclosing scope
```
After that error application is served.

I found that `exc` variable to which exception is assigned becomes unavailable when leaving `except:` clause, even for nested functions. When I attach that same exception to another (temporary) variable, everything works fine:
```
diff --git a/muffin/app.py b/muffin/app.py
index b966f0c..c106f1b 100644
--- a/muffin/app.py
+++ b/muffin/app.py
@@ -127,8 +127,9 @@ class Application(web.Application):

             except ImportError as exc:
                 config.CONFIG = None
+                exc_save = exc  # or else it will be unavailable on Python 3.5
                 self.register_on_start(
-                    lambda app: app.logger.error("Error importing %s: %s", module, exc))
+                    lambda app: app.logger.error("Error importing %s: %s", module, exc_save))

         return config
```
results in this output:
```
[2016-03-16 05:54:25 +0300] [11874] [INFO] Starting gunicorn 19.4.5
[2016-03-16 05:54:25 +0300] [11874] [INFO] Listening at: http://0.0.0.0:5002 (11874)
[2016-03-16 05:54:25 +0300] [11874] [INFO] Using worker: muffin.worker.GunicornWorker
[2016-03-16 05:54:25 +0300] [11882] [INFO] Booting worker with pid: 11882
[2016-03-16 05:54:25 +0300] [11882] [ERROR] Error importing app_cfg: No module named 'app_cfg'
```

For me that error message looks very strange, because I coultn't find any references to `exc` variable in any of enclosing scopes... May it be a bug in Python?
My patch helps to workaround this issue, but is ugly..

**Comment by klen** [comment]
Thank you for the report!
